### ISSUE TITLE
honeyhunterworld.com

### ISSUE THREAD

**Issue by Corrodias** [LiCybora/NanoDefenderFirefox#102]
### Test link (required):
https://honeyhunterworld.com/mhwb/

### Screenshot of the web page (including address bar and extension icons) (required):
https://i.imgur.com/tHz1x7j.png

### Screenshot of the console (press `F12` to bring up the console) (required):
https://i.imgur.com/P8r6V8G.png

### Explain what was not right (optional if obvious):
It should proceed to the next screen, but instead it stops at this point. This works in Chrome, using the Chrome versions of Nano Adblocker and Nano Defender.

### Environment (Required):
- Operating System and Version: Windows 7 x64, SP1, latest updates as of a month or so ago
- Browser and Version:  Firefox, 65.0.1, 64-bit. This site works in Chrome.
- Adblocker and Version: Nano Adblocker 1.0.0.87 and Nano Defender, v15.0.0.94 (AMO only). .93 from GitHub exhibits the same problem.

#### Your filter lists (Required):
https://i.imgur.com/PrN0AZx.png

### Add everything else that you believe to be useful below (optional):
The site works if the site is whitelisted in Nano Adblocker. The site works in the current version of Chrome with Nano Adblocker and Nano Defender from the "web store".

**Comment by LiCybora** [comment]
I don't know what's wrong actually, need some time for check. But interesting thing is once I forgot copy the https, it pass the checking and do not stuck...
![image](https://user-images.githubusercontent.com/40160522/52911208-b5c00e00-32db-11e9-9903-db064ca966fd.png)
This is NOT a solution, just interesting findings from accident...

**Comment by Corrodias** [comment]
Huh. I agree, that is strange. Normally I would think that suggests it's a problem trying to load an HTTP resource on a HTTPS page, but the console has no errors about that, and I wouldn't think that would affect Nano Adblocker or Defender, regardless.

**Comment by LiCybora** [comment]
Race condition. No idea why Chromium always win while Firefox usually if not always lose the race (even http is not always works).

Fine, I will find try some ways to deal with it. Please wait next version release for fix.

**Comment by jspenguin2017** [comment]
Make sure you cache the real `setTimeout` function, so websites / scriptlets can't mess with it.

**Comment by Corrodias** [comment]
Nice job. I know race conditions can be brutal to diagnose and fix.
