### ISSUE TITLE
expansion.com

### ISSUE THREAD

**Issue by JoseHidalgo** [LiCybora/NanoDefenderFirefox#112]
### Explain what was not right (optional if obvious):
The page loads normally. Then about 20 secs later, the pop-up appears and I have to reload the page and scroll down again to keep reading for another 20 seconds. Very annoying.

### Environment (Required):

- Operating System and Version: Window 7 SP1 x64
- Browser and Version: Firefox 61.0.2
- Adblocker and Version: uBlock Origin 1.18.4 + Nano Defender 15.0.0.106

**Comment by LiCybora** [comment]
![image](https://user-images.githubusercontent.com/40160522/54074813-28684c00-42d2-11e9-86ec-942fe352a96d.png)

It works fine for me, no waiting pop-ups even scroll to end of each article. No pop-up for me even wait for long.

**Comment by JoseHidalgo** [comment]
Agreed. So what could be wrong in my case ? My screen + console proves that I'm not dreaming, lol

**Comment by LiCybora** [comment]
May I know have you follow the [extra installation steps](https://jspenguin2017.github.io/uBlockProtector/#extra-installation-steps-for-ublock-origin)? (Although I can't reproduce with uBO only either, so not important for this case)

Try clear cache (and possibly Cookies) to retry? Sometimes they may be the issue. Other addons may interfere it.

**Comment by JoseHidalgo** [comment]
Yes, I had followed the extra steps.
So I have cleared caches (in uBlock Origin and in Firefox) & cookies, and reloaded filter lists.
Amazingly, now it works ! Problem solved (for now, lol).
