### ISSUE TITLE
indiatimes.com

### ISSUE THREAD

**Issue by ghajini** [LiCybora/NanoDefenderFirefox#113]
### Test link (required):
`https://timesofindia.indiatimes.com/india/terror-financing-nia-summons-mirwaiz-geelanis-son-for-questioning-in-delhi/articleshow/68334840.cms`
`https://economictimes.indiatimes.com/news/international/business/chinas-gdp-growth-pace-was-inflated-for-nine-years-study-finds/articleshow/68330636.cms`
`https://navbharattimes.indiatimes.com/business/business-news/surat-metro-rail-project-approves-government/articleshow/68337333.cms`
`https://punemirror.indiatimes.com/news/india/nia-summons-hurriyat-m-chairman-mirwaiz-umar-farooq-to-new-delhi/articleshow/68336205.cms`
`https://maharashtratimes.indiatimes.com/business/business-news/salary-increments-in-most-sectors-likely-to-be-higher-than-last-year-says-aon-survey/articleshow/68336840.cms`
`https://eisamay.indiatimes.com/nation/rahul-gandhi-asks-pm-modi-to-tell-nation-who-released-masood-azhar-from-jail/articleshow/68337561.cms`
`https://vijaykarnataka.indiatimes.com/business/news/pnb-scamster-nirav-modi-tracked-down-to-swanky-london-apartment-uk-home-secretary-cerifices-indias-extradition-request/articleshow/68337466.cms`

### Screenshot of the web page (including address bar and extension icons) (required):

![Screenshot (124)](https://user-images.githubusercontent.com/20338483/54075492-023caf00-42c6-11e9-80fe-8f120bbf01f8.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![Screenshot (125)](https://user-images.githubusercontent.com/20338483/54075540-ba6a5780-42c6-11e9-8723-e50e1914e28e.png)
![Screenshot (126)](https://user-images.githubusercontent.com/20338483/54075541-ba6a5780-42c6-11e9-9005-3ea505f96ed3.png)

### Explain what was not right (optional if obvious):

`from around the web` ads, some of them has legitimate news content and other are purely ads
### Reproduction steps (optional if trivial):
going above , scroll down below to see around the web ads

### Environment (Required):

- Operating System and Version: win 10
- Browser and Version: firefox 65
- Adblocker and Version: ublock origin 1.18.4

#### Your filter lists (Required):

the default settings+ those required for nano defender to work(nano defeneder integration,whitelist,nano filters)

### Add everything else that you believe to be useful below (optional):
`promoted stories` over here
`https://www.indiatimes.com/news/india/former-navy-chief-writes-to-election-commission-to-stop-misuse-of-armed-forces-in-polls-363444.html`

**Comment by LiCybora** [comment]
Purge cache and force update your filters. Should be fixed recently.
Related: NanoMeow/QuickReports#782

**Comment by ghajini** [comment]
Like I said other sites are not fixed in that commit I reported above......

Also Firefox android has these ads despite that filter

**Comment by LiCybora** [comment]
Most of your reported sites are fixed except the following 3:

NanoMeow/QuickReports#784
NanoMeow/QuickReports#786
`https://www.indiatimes.com/news/india/former-navy-chief-writes-to-election-commission-to-stop-misuse-of-armed-forces-in-polls-363444.html`

Regarding for Firefox Android issue, I don't have an Android device, though I can test it in emulator. It may takes some time as I don't even use Android for long.

**Comment by ghajini** [comment]
Fixed upstream at uassets repo......
