### ISSUE TITLE
washingtonpost.com: detects NanoDefender as adblocker

### ISSUE THREAD

**Issue by PurpleObelisk** [LiCybora/NanoDefenderFirefox#139]
### Test link (required):
https://www.washingtonpost.com/business/2019/05/31/millennials-have-an-average-net-worth-thats-significantly-less-than-previous-generations/?utm_term=.02d6adda163b

### Screenshot of the web page (including address bar and extension icons) (required):
<img width="1879" alt="wapo" src="https://user-images.githubusercontent.com/51244901/58726905-ca5e7880-8397-11e9-8436-6b9f2953f9ce.png">

### Screenshot of the console (press `F12` to bring up the console) (required):
<img width="1879" alt="console" src="https://user-images.githubusercontent.com/51244901/58727028-114c6e00-8398-11e9-9519-cc8a5243f393.png">

### Explain what was not right (optional if obvious):
It seems like Defender should prevent this from appearing.

### Reproduction steps (optional if trivial):
Visit URL. Nano Adblocker can be enabled or disabled (clicking power icon in extension GUI) and the site's alert will appear.

### Environment (Required):
- Mac OS X 10.14.5
- Firefox Nightly (69.0a1 (2019-05-31) (64-bit))
- Nano Defender 15.0.0.147
- Nano Adblocker 1.0.0.112

#### Your filter lists (Required):
default

#### Your custom filters (Required if you have any):
none

#### Your other extensions (Required if you have any):
1Password

### Add everything else that you believe to be useful below (optional):
Thank you for your work! 😄 👍

**Comment by LiCybora** [comment]
From your screenshot, it is blocked by Firefox Tracking Protection, not Nano Defender.
Reason: I can also reproduce without any extension
![image](https://user-images.githubusercontent.com/40160522/58755955-34eef000-8521-11e9-9afd-796594b52905.png)
With Tracking Protection off, I cannot reproduce, regardless Adblocker on or off.
![image](https://user-images.githubusercontent.com/40160522/58755987-99aa4a80-8521-11e9-9261-95a907e7bbe4.png)

**Comment by Rihcus** [comment]
Same issue

**Comment by LiCybora** [comment]
With updated rules, works fine for me even with Firefox Tracking Protection on.
