### ISSUE TITLE
a2zapk.com, unlockapk.com

### ISSUE THREAD

**Issue by SeriousHoax** [LiCybora/NanoDefenderFirefox#155]
### Test link (required):
 
https://a2zapk.com/608717-stellarium-mobile-free-star-map-1-2-4-a2z.html
https://unlockapk.com/dl3/
### Screenshot of the web page (including address bar and extension icons) (required):
 
![g](https://user-images.githubusercontent.com/29574622/67140055-81d92600-f278-11e9-9e65-c0f64f662d06.PNG)

### Screenshot of the console (press `F12` to bring up the console) (required):
 
![s](https://user-images.githubusercontent.com/29574622/67140099-e2686300-f278-11e9-8925-b88ab9be9fcc.PNG)

### Explain what was not right (optional if obvious):
The site is detecting adblocker

### Reproduction steps (optional if trivial):
To reproduce this, visit this link as an example: https://a2zapk.com/569808-stellarium-mobile-free-star-map-1-2-6-a2z.html 
Click on the "Go To Download Page" and the following page would show Adblock Detect.

### Environment (Required):

- Operating System and Version: Windows 10 Pro 1903
- Browser and Version: Firefox Developer Edition 71
- Adblocker and Version: uBlock Origin 1.22.4

#### Your filter lists (Required):
 
![1](https://user-images.githubusercontent.com/29574622/67140131-36734780-f279-11e9-905b-494b1f1775c8.PNG)
![2](https://user-images.githubusercontent.com/29574622/67140132-36734780-f279-11e9-877b-03d4e714f7f7.PNG)

#### Your other extensions (Required if you have any):
uMatrix

**Comment by llacb47** [comment]
Update your filters

**Comment by SeriousHoax** [comment]
> 
> 
> Update your filters

Everything is up to date. 
Btw, the link that I gave seems to have changed. You may try this link instead: https://a2zapk.com/608864-stellarium-mobile-plus-star-map-1-2-10-patched-arm64-a2z.html

**Comment by llacb47** [comment]
Still works fine for me.

**Comment by LiCybora** [comment]
Try disable Firefox tracking protection for that site. Works fine for me when that is disabled.
