### ISSUE TITLE
[Anti-adblock] strims.world

### ISSUE THREAD

**Issue by Majkovsky** [LiCybora/NanoDefenderFirefox#160]
http://strims.world/SkokiKwalifikacje.php?source=1

**"BRAK PLAYERA? WYŁĄCZ ADBLOCKA!"**

Nano Defender **15.0.0.170**
Mozilla Firefox **71.0**

**Comment by LiCybora** [comment]
Can you fill in the template with screenshot and step to reproduce?

I cannot read those language and don't know which button to click. I just see list of links but do not see those wordings.

**Comment by LiCybora** [comment]
Closing due to incomplete report. May reopen once required information is filled.
