### ISSUE TITLE
Nano Defender Pro rejected by AMO

### ISSUE THREAD

**Issue by LiCybora** [LiCybora/NanoDefenderFirefox#167]
```
Details:
This version did not pass the review because of the following issues:

1) eval uses are generally not allowed for security and performance reasons. eval is only necessary in rare cases. Please use a different method or explain why eval is required in your add-on.
For more information: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#Never_use_eval!

```

TBH, `eval` exist only three times, while two are patching the eval function to prevent further detection of adblocker instead of calling `eval`. The remaining one will call eval due to the replacement of function name for bypassing detection. Maybe they think is one is problematic.

The only workaround now is to disable the remaining one rule which is actually use of `eval`.

**Comment by jspenguin2017** [comment]
The Pro version is expected to contain all rules, including calls to `eval` and page scope (main world) functions. If you're unable to publish the Pro version, feel free to publish the standard version.

**Comment by jspenguin2017** [comment]
Another option would be to add more build names (Lite, Standard, Pro, Ultimate, etc.), what I want to avoid is the same build name meaning different things.

**Comment by LiCybora** [comment]
I apologize for claiming as "Pro" too early. I just do not expect they ban it too suddenly.

Publishing standard version might overkill, at least for now as just one rule. Changing build name may be a better option, but those names behind might confuse user. How about using browser name as build name (e.g. Nano Defender Firefox)? Another benefit for this is I can add browser-specific features/rules.

I will still publish self-signed Pro on GitHub with all rules. Only the AMO edition will need to be rename.

**Comment by jspenguin2017** [comment]
Yep, that sounds good to me. Just put a note in the README explaining the differences so people won't get confused.
