### ISSUE TITLE
Detect AD Block

### ISSUE THREAD

**Issue by fairyenzy** [LiCybora/NanoDefenderFirefox#171]
Plz fix this site
https://freedoge.io
![Screenshot_Kiwi_Browser_20200309-152614](https://user-images.githubusercontent.com/61671678/76195210-b6c22700-61df-11ea-9f99-a2be6b517344.png)

**Comment by llacb47** [comment]
@mapx-

**Comment by LiCybora** [comment]
Thx. Closing as fixed.
