### ISSUE TITLE
Links in "additional stepps if using uBlock Origin" are not working

### ISSUE THREAD

**Issue by mato200** [LiCybora/NanoDefenderFirefox#175]
I am following a guide on how to install and in additional stepps the links provided dont open.
How do add them, do i just click the link or do i need to decode the URL and paste it/import in uBlock Origin Filter list ??

https://jspenguin2017.github.io/uBlockProtector/#extra-installation-steps-for-ublock-origin

e.g. https://easylist-downloads.adblockplus.org/antiadblockfilters.txt&title=Adblock%20Warning%20Removal%20List is 404 not found

**Comment by gwarser** [comment]
Click the link. This is special subscription link, not webpage address.

**Comment by mato200** [comment]
ty very much, now it all works , i have set it up
