### ISSUE TITLE
cant update the filterlists for uBlock Origin

### ISSUE THREAD

**Issue by Jorge9811** [LiCybora/NanoDefenderFirefox#178]
Title.
I installed Firefox ESR and been importing my stuff from my main installation of Firefox. When the time to install Nano Defender came _(turns out I was using it wrong all along, as I thought that I didn't need the NanoDefenderFirefox addon if I used the filterlists for uBO btw)_, I noticed that I can't update the filterlists in uBO. Judging by how they're being displayed as full links, I'm guessing they're not working at all.
![firefox-2020-06-05_11-35-11](https://user-images.githubusercontent.com/54429803/83889406-7e1fe400-a721-11ea-8ee7-e863b927068f.png)

**Comment by LiCybora** [comment]
![image](https://user-images.githubusercontent.com/40160522/83943237-0dfe8480-a82d-11ea-93ed-cdd25cda5627.png)
I cannot reproduce. If there is still issue, try remove them and re-subscribe from [Extra installation steps for uBlock Origin](https://jspenguin2017.github.io/uBlockProtector/#extra-installation-steps-for-ublock-origin).

If issue still continue, make sure you can access the URL shown in your image.
