### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by AliceDTRH** [LiCybora/NanoDefenderFirefox#190]
@LiCybora 

I wanted to thank you for the amazing decision to stop updating your extension!
As you may or may not know, the new owners of Nano Defender added malware to their version and compromised a lot of accounts. Because you decided to inform people by changing your extension to alert people and stopping the updates you saved my (and a lot of other people's) login cookies.

Thank you!

More info: 
https://github.com/jspenguin2017/Snippets/issues/5
https://tweakers.net/nieuws/173620/nano-adblocker-op-chrome-bevat-na-overname-malware-die-instagram-likes-uitdeelt.html (Dutch news article)

**Comment by gen-angry** [comment]
Yep, thank you! 👍 

Luckily, I hadn't got to migrating my family's Chrome extensions at the time and was relieved to see that you had prevented Firefox users from the same fate. Laziness paid off for once!
