### ISSUE TITLE
https://www.libremercado.com/

### ISSUE THREAD

**Issue by JoseHidalgo** [LiCybora/NanoDefenderFirefox#194]
### Screenshot of the web page (including address bar and extension icons) (required):
![2020 11 25 - 23 42 17](https://user-images.githubusercontent.com/10851603/100289146-8e01dd80-2f78-11eb-8dfc-0fa8cdfc8b89.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2020 11 25 - 23 44 29](https://user-images.githubusercontent.com/10851603/100289158-9528eb80-2f78-11eb-8600-319f1d04b907.png)

### Environment (Required):
- Operating System and Version: Windows 7 SP1 x64
- Browser and Version: Firefox 82.0.3 (64 bits)
- Adblocker and Version: µBlock Origin 1.31.0
- Nano Defender Version: Nano Defender Pro 15.0.0.206

#### Your filter lists (Required):
![2020 11 25 - 23 49 35](https://user-images.githubusercontent.com/10851603/100289359-f9e44600-2f78-11eb-8d0f-e7738165942f.png)

### Add everything else that you believe to be useful below (optional):
Usually it all works fine. But today I noticed that the aforementioned domain wasn't working.
Let me know if you need any more info.
Thanks in advance.

**Comment by mapx-** [comment]
spanish site, already fixed here:
`spa, por: AdGuard Spanish/Portuguese`

**Comment by JoseHidalgo** [comment]
Got it. Silly me ! It works now.
But the bottom banner ad still remains (I think that's rather a µBlock Origin issue, right ?).

**Comment by mapx-** [comment]
uBO issue ? :) no, you have to report it at the right repository:
https://github.com/AdguardTeam/AdguardFilters/issues

or add as custom filter:

`libremercado.com###estrategias`

**Comment by JoseHidalgo** [comment]
Thanks ! Added it as custom filter. Everything seems to work now. Case closed I guess. :)
