### ISSUE TITLE
beelink.in

### ISSUE THREAD

**Issue by Sopor** [LiCybora/NanoDefenderFirefox#197]
### Test link (required):
https://beelink.in

### Screenshot of the web page (including address bar and extension icons) (required):

![image](https://user-images.githubusercontent.com/5789283/102368204-e433d080-3fba-11eb-8b9b-6a9107ff0e9b.png)

### Environment (Required):
- Operating System and Version: Windows 10
- Browser and Version: Firefox 84
- Adblocker and Version: uBlock Origin 1.31.0
- Nano Defender Version: 15.0.0.206

#### Your filter lists (Required):
- [x] uBlock filters
- [x] uBlock filters – Annoyances​​​​​
- [x] uBlock filters – Badware risks​
- [x] uBlock filters – Privacy​​​​​
- [x] uBlock filters – Resource abuse​​​​​
- [x] uBlock filters – Unbreak​​​​​
- [x] Adblock Warning Removal List
- [x] EasyPrivacy
- [x] Malware Domain List
- [x] Malware domains
- [x] Fanboy’s Annoyance List
- [x] Peter Lowe’s Ad and tracking server list
- [x] SWE: Frellwit's Swedish Filter​​​​​
- [x] Nano Defender Integration
- [x] Nano Filter
- [x] Nano Filters - Whitelist

#### Your other extensions (Required if you have any):
Parent folder
Tab session manager
URLs list
WEAlias
Undo close tab
Persistent video/audio volume

**Comment by mapx-** [comment]
fixed, update uBO filters
https://github.com/uBlockOrigin/uAssets/commit/956483a5c8b5b0c9fbe5f52f6e26bad87ae5ae87
