### ISSUE TITLE
White space

### ISSUE THREAD

**Issue by Feky** [LiCybora/NanoDefenderFirefox#21]
Hi

I love this extension but have Firefox problem, not on Chrome and its extra white space that looks ugly can you fix it? Thanks :)

![whitespace](https://user-images.githubusercontent.com/3746977/42430491-e73ee0c4-833f-11e8-9fdb-e3d8eabf7873.png)

**Comment by LiCybora** [comment]
The problem occurs when extension is placed inside overflow. Seems all extension popups being opened inside overflow will have fixed width, which does not match the design of origin popup width. You may also try other addons might also have similar problem.

The current workaround is put it outside the overflow. I will try to fix it in later version.

**Comment by LiCybora** [comment]
Fix will take effect on next version, or you can test the unsigned pre-release version.

Preview:
![image](https://user-images.githubusercontent.com/40160522/42435153-4950d4a0-8388-11e8-86e3-016176d5702e.png)
