### ISSUE TITLE
Package for Palemoon/Basilisk

### ISSUE THREAD

**Issue by RomanHargrave** [LiCybora/NanoDefenderFirefox#30]
This is what #19 appears to be about, to the tee.

Palemoon and Basilisk are two pre-servo forks of firefox, which are used by people who require XUL/NPAPI plugin support. Palemoon, if I recall, totally lacks web extension support, while Basilisk does support basic web extensions, although the packaging for the extension would need to be adjusted.

Nearly all PM/Basilisk users are using some manner of advertisement blocking, so I can only presume that you will get more indecipherable requests.

**Comment by LiCybora** [comment]
Closing as no feedback for 48 hours and treat as the method fix installation for Basilisk.

**Comment by FrostKnight** [comment]
Hey, LiCybora, do you know if there is anyone capable who could make a close as possible clone to Nano Defender for Palemoon/Basilisk?

PS, if you were to make even ONE! one version that would be good enough to be updated like nano adblocker/easily by palemoon or some other group, I would more than consider paying you for said services. Let me know your thoughts on this.  I don't expect perfection, but if its good enough that either A: (Hyperbola.info) thinks its worth something or B: Palemoon.org is interested, I will give you 35$. Tell me if your interested.

I really would love an anti adblock killer type script for palemoon/basilisk. Perhaps the original author and other people would be interested in paying for this.  Dunno... I am in though if your interested.

**Comment by LiCybora** [comment]
Sorry that I cannot find one can make that clone for you. This addon start at web extension is not easy revert back to legacy XUL. I also doubt that those legacy browsers have sufficient APIs allow for rewriting HTML element/attribute (maybe yes, but need lots time to learn whole API). Also I don't use those browser personally so developing those version is not my priority.

I don't want this job become a paid job or else I owed you something, so the bounty may reserve to others. You may also look for someone that use palemoon/basilisk personally as they may more familiar with those browser and more capable for the job.

**Comment by FrostKnight** [comment]
@LiCybora... Okay fair enough, understood... Perhaps I should look elsewhere.  ;/

Thank you for responding though.
