### ISSUE TITLE
[Anti-adblock] winteriscoming.net

### ISSUE THREAD

**Issue by Ahmed0425** [LiCybora/NanoDefenderFirefox#34]
### Test link (required):
https://winteriscoming.net/
### Screenshot of the web page (including address bar and extension icons) (required):
https://imgur.com/On5uxZF
### Screenshot of the console (press `F12` to bring up the console) (required):
https://imgur.com/4D5AZvC
### Environment (Required):

- Operating System and Version: Win10 Pro
- Browser and Version: Firefox 60.1.0esr
- Adblocker and Version: ublock origin 1.16.14

#### Your filter lists (Required):
List filters you have enabled or disabled from the default settings
uBlock filters​​​​​​​
uBlock filters – Badware risks​
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
Adblock Warning Removal List​
EasyList​
EasyPrivacy​
Malware Domain List
Malware domains​
​​​​ara: Liste AR​
Nano Defender Integration​​
Nano filters​​
Nano filters - Whitelist​​

**Comment by LiCybora** [comment]
> Doesn't work on many sites since v15

I checked this domain never in Nano Defender even in v14.

By the way, add `||gammamaximum.com^$third-party`

**Comment by LiCybora** [comment]
Close as fixed

**Comment by Ahmed0425** [comment]
I didn't know about the rule .. tnx as this fixed it
Would you tell me which filter list has this rule?

**Comment by LiCybora** [comment]
Should be included in uBlock filters. Try force update it if it not work.
