### ISSUE TITLE
Updates not working on Windows 10

### ISSUE THREAD

**Issue by TonyTough** [LiCybora/NanoDefenderFirefox#42]
This extension works for me great on Windows 7 pro (64bit) + Firefox 61.0.1 (64bit) and updates itself in Firefox.

On a Windows 10 pro (64bit) system the auto-update in Firefox doesn't work (updates are never found) and even with manually downloading the newest version and installing it, there are problems: 
If I click on the newest xpi-file on github and allow Firefox to install the extension from github, then there is a popup in Firefox that says because of a connection error the add-on couldn't be downloaded.
So I always have to download it via right-click first, and then install the new version by double-clicking the downloaded xpi-file.

**Comment by LiCybora** [comment]
![image](https://user-images.githubusercontent.com/40160522/43507372-8667bcf4-959f-11e8-989a-d1166afa3461.png)
It works fine for me. Have you modify the default settings in Firefox? If you still get same issues with new profile and default settings, show me the screenshot.

**Comment by TonyTough** [comment]
Hello,

I have now tried a new profile with default settings and there indeed it fully works.
So it must indeed have to do with my profile settings.

Has anyone an idea which setting I have to change?

**Comment by TonyTough** [comment]
I checked out further and found out, that after rebooting the PC the exact same problem occurs again.
So the solution in my previous posting is not working.

So I searched the internet for several hours and tried many things and finally found the solution:

Adding the following lines in about:config with boolean false in Firefox resolves the issue:
**extensions.install.requireBuiltInCerts false
extensions.update.requireBuiltInCerts false**

**Comment by LiCybora** [comment]
Sorry for missing your post. Seems the problem does not bind with Windows 10, but the MITM proxy server.
