### ISSUE TITLE
gentside and ohmymag

### ISSUE THREAD

**Issue by beenmoov** [LiCybora/NanoDefenderFirefox#47]
https://www.ohmymag.com/squeezie/squeezie-des-youtubeurs-profiteraient-de-leur-notoriete-pour-avoir-des-rapports-sexuels-avec-des-mineurs_art119888.html?utm_campaign=audiencey&utm_medium=Social&utm_source=Facebook#Echobox=1533654493

Gentside.com and OHmymag.com

https://imgur.com/X9PvM2b

**Comment by LiCybora** [comment]
Add:
```
ohmymag.com, gentside.com###adblocker
ohmymag.com, gentside.com##body:style(overflow-y: auto !important;)
ohmymag.com, gentside.com##script:inject(set-constant.js, ADBLOCK_ENABLED, false)
```

I know these are bad solutions but I am not good at writing filter rules. Should I @okiehsch for help?

**Comment by okiehsch** [comment]
Why do you think this is a bad solution, is something broken?

If not I will add your filters as they are 👍

**Comment by LiCybora** [comment]
Thx, nothing is broken in my view but seems detection still here,  maybe not an optimal solution to 'hidden' the use of adblocker.
Anyway, closing as fixed.
