### ISSUE TITLE
Auto-update and availability on AMO

### ISSUE THREAD

**Issue by IoanPaleru** [LiCybora/NanoDefenderFirefox#49]
Hi. Why doesn't Nano Defender for firefox update automatically, and why isn't it on the firefox add-ons website? Thanks.

**Comment by LiCybora** [comment]
> Why doesn't Nano Defender for firefox update automatically

No, Nano Defender for Firefox do update automatically. Keep in mind that default Firefox check addons update once per day only. If you want to change this, see https://github.com/LiCybora/NanoDefenderFirefox/issues/25#issuecomment-405073256.

> why isn't it on the firefox add-ons website?

Duplicate with #23.

**Comment by TonyTough** [comment]
Auto-update indeed doesn't work on some system configurations.

Adding the following lines in about:config with boolean false in Firefox resolved the issue for me:
**extensions.install.requireBuiltInCerts false
extensions.update.requireBuiltInCerts false**

See also the following links:
https://bugzilla.mozilla.org/show_bug.cgi?id=1403075
mozilla/addons-frontend#3867

**Comment by LiCybora** [comment]
Due to incompatibility, auto-update in legacy browser will not work. I don't find any hack to bypass it.
