### ISSUE TITLE
Name confusion of Nano Defender vs uBlock Protector

### ISSUE THREAD

**Issue by IoanPaleru** [LiCybora/NanoDefenderFirefox#50]
Hi. Why do you keep changing the name of Nano Defender? It used to be called uBlock Protector. You shouldn't change the name of it anymore, because it's confusing for people. Thanks.

**Comment by LiCybora** [comment]
For asking question, please focus asking in one issue next time.

> Why do you keep changing the name of Nano Defender?

No, I don't change the name. The product really named Nano Defender. It is already explained why the repository keep using the name uBlock Protector in [upstream](https://github.com/jspenguin2017/uBlockProtector). The product name in [homepage](https://jspenguin2017.github.io/uBlockProtector/), and the Chromium one in [Google Store](https://chrome.google.com/webstore/detail/nano-defender/ggolfgbegefeeoocgjbmkembbncoadlb) is Nano Defender.

> You shouldn't change the name of it anymore, because it's confusing for people

You may be new to here and don't know the history of Nano Defender on Firefox. Right before me there is another maintainer forked the upstream project which use the name NanoDefenderFirefox as repository name (now deleted). I believe change it back to uBlockProtector confuse even more people. Moreover, as the product already renamed to Nano Defender, it is more suitable to keep using NanoDefenderFirefox as the repository name.
