### ISSUE TITLE
I cannot download NanoDefender for Firefox

### ISSUE THREAD

**Issue by andrewxyxyxy** [LiCybora/NanoDefenderFirefox#51]
It returns me a connection error when I try to download the .xpi file

![immagine](https://user-images.githubusercontent.com/26189057/44001559-c8ef2ea2-9e34-11e8-9a96-01d0701494ad.png)

**Comment by LiCybora** [comment]
![image](https://user-images.githubusercontent.com/40160522/44001592-a9de920e-9e67-11e8-95f2-7fbb624b75bc.png)

It works fines for me. Try right click and "save as" into your local drive, and `about:addons` click `Install add-on from files`

![image](https://user-images.githubusercontent.com/40160522/44001612-f85574e8-9e67-11e8-8bfe-83e051df0499.png)

By the way, your problem similar to the one in #42. You may also try the solution inside that issue.

**Comment by andrewxyxyxy** [comment]
This works! Thank you
