### ISSUE TITLE
[Request] Waterfox support

### ISSUE THREAD

**Issue by eleius** [LiCybora/NanoDefenderFirefox#64]
I use uBlock Origin in the Waterfox browser (Firefox fork) and would like to install Nano Defender too, but for some reason Waterfox reports it as "incompatible". I'd appreciate if it could be make compatible in a future version.

**Comment by xlollomanx** [comment]
If I remember correctly waterfox use non-quantum firefox as a base (so firefox 56), and If I'm not wrong nano defender need some code present in ff 57 and newer. In addition jspenguin dropped support for firefox, so I don't think he will do that in any case.

**Comment by LiCybora** [comment]
[Another post](https://github.com/LiCybora/NanoDefenderFirefox/issues/30#issuecomment-405822737) explain the reason why it is incompatible. A force installation method is also provided, see if you have any luck, **but you take your own risk**.
