### ISSUE TITLE
NanoDefender Prevent Some Imbedded Videos To Play

### ISSUE THREAD

**Issue by Heri0n** [LiCybora/NanoDefenderFirefox#69]
### Test link (required):

https://www.boursorama.com/videos/actualites/la-fed-est-elle-vraiment-folle-comme-l-affirme-trump-f5bd59528781f0adda22b85ffac69b7f

### Screenshot of the web page (including address bar and extension icons) (required):

https://pasteboard.co/HICoQmH.jpg
Page with ND disabled

### Screenshot of the console (press `F12` to bring up the console) (required):

https://pasteboard.co/HICkN6B.jpg
Console with ND Enabled

https://pasteboard.co/HICltnG.jpg 
Console with ND Disabled

### Explain what was not right (optional if obvious):
Enabling ND prevent the embedded videos on site boursorama.com to be played. As soon as I disable ND and reload the pages, the videos can be played.

### Environment (Required):

- Operating System and Version: Win 7 64-bit
- Browser and Version:  FF 62
- Adblocker and Version:  NanoAdblocker 1.0.0.70

#### Your filter lists (Required):
 
Only default settings

**Comment by jspenguin2017** [comment]
Works fine on Chrome. What is the version of ND that you are using? 
![image](https://user-images.githubusercontent.com/7283682/46981387-51731080-d095-11e8-890d-a367cbd60f29.png)

**Comment by jspenguin2017** [comment]
What is the version of ND that you are using?

**Comment by LiCybora** [comment]
I can reproduce with the current version of ND. The problem seems to be the rule of "ultimedia.com". Commenting it resolve the problem but not sure whether it is safe (cannot found this domain in any Nano/uAssets issue). There is also an issue in legacy Aak for this domain, but don't know when was this rule added.

Please wait for next version release for fix.

**Comment by jspenguin2017** [comment]
That's weird, it works fine on Chrome for me. I'll see if removing the rule breaks stuff on Chrome.

**Comment by jspenguin2017** [comment]
Works fine without the rule on Chrome. I'll just remove it.

**Comment by Heri0n** [comment]
It works now... Thank You Guys !!
