### ISSUE TITLE
[anti-adblock] realcleardefense.com

### ISSUE THREAD

**Issue by Shinzawaii** [LiCybora/NanoDefenderFirefox#82]
### Test link (required):
[https://www.realcleardefense.com/](url)

### Screenshot of the web page (including address bar and extension icons) (required):

![](https://i.imgur.com/wIm6r5X.png)

### Screenshot of the console (press `F12` to bring up the console) (required):

![](https://i.imgur.com/KOjczoZ.png)

### Explain what was not right (optional if obvious):
Detects ad block and increases 'max article count' per pageview/refresh not even clicked article

### Reproduction steps (optional if trivial):
Go to and/or refresh page

### Environment (Required):

- Operating System and Version: W10
- Browser and Version: Chrome Version 72.0.3610.2
- Adblocker and Version: uBlock origin 1.17.0 nano defender 15.0.0.78

#### Your filter lists (Required):

uBlock filters​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
EasyList​​​​​
EasyPrivacy​​​​​
Malware Domain List​​​​​
Malware domains​​​​​
Peter Lowe’s Ad and tracking server list​​​​​

#### Your custom filters (Required if you have any):
! 11/16/2018, 3:10:52 PM https://www.forbes.com/sites/lorenthompson/2018/11/15/if-americas-military-loses-world-war-iii-low-readiness-will-likely-be-the-reason/#43db5c486bae
www.forbes.com###brightcove_perform_0_html5_api

! 11/16/2018, 3:11:00 PM https://www.forbes.com/sites/lorenthompson/2018/11/15/if-americas-military-loses-world-war-iii-low-readiness-will-likely-be-the-reason/#43db5c486bae
www.forbes.com###brightcove_perform_0

**Comment by LiCybora** [comment]
It works fine for me.
![image](https://user-images.githubusercontent.com/40160522/49198135-c348b480-f3cc-11e8-81b6-3342809ab93b.png)


Two problems for you:
1. From your filter lists, neither Adblock Warning Removal List, Nano Filter nor Nano Defender Integration is not included. I guess you miss some installation steps, please read https://jspenguin2017.github.io/uBlockProtector/#extra-installation-steps-for-ublock-origin and follow all steps and try again.
2. Seems you are using Chrome but here is Firefox repo, although I will still forward to the right person this time @jspenguin2017, please report to right repository [here](https://github.com/NanoAdblocker/NanoFilters/issues) next time. (But this time, don't open extra issue on there.)

**Comment by Shinzawaii** [comment]
Hmm I could have sworn to have followed those steps when installing. Anyway, did exactly -that^- again and it seems to work now.
Excuse me for the lack of due diligence in checking those steps again first myself (and additionally posting in the wrong repo section) but thanks for the help!

Solved.

**Comment by jspenguin2017** [comment]
I can't reproduce neither.
