### ISSUE TITLE
how to sync or backup Nano Defender for Firefox and Nano Adblocker Core for Firefox?

### ISSUE THREAD

**Issue by candrapersada** [LiCybora/NanoDefenderFirefox#86]
how to sync or backup addons Nano Defender for Firefox and addons Nano Adblocker Core for Firefox?

**Comment by LiCybora** [comment]
Duplicate with LiCybora/NanoCoreFirefox#14. Next time please just ask on one repo without duplicate as I keep watch both.

As Nano Defender is not customizable at the time of this comment, a backup is not quite necessary. I will just close this and if you have further question go ask on another side instead.
