### ISSUE TITLE
[anti-adblock] whoer.net

### ISSUE THREAD

**Issue by aydybb** [LiCybora/NanoDefenderFirefox#88]
### Test link (required):
https://whoer.net

### Screenshot of the web page (including address bar and extension icons) (required):
https://imgur.com/TEjnGov

### Screenshot of the console (press `F12` to bring up the console) (required):
https://imgur.com/fImwVjc

### Explain what was not right (optional if obvious):
Detects ad block

### Environment (Required):

- Operating System and Version: Win7
- Browser and Version: Firefox 60.4.0esr
- Adblocker and Version: uBlock Origin 1.17.4 & Nano Defender 15.0.0.81

#### Your filter lists (Required):
https://imgur.com/a/YxaS1P6
https://imgur.com/a/IpbH1XO

**Comment by LiCybora** [comment]
A testing page is very likely not going to be resolved unless it is a very common method for adblocking detection. Otherwise fixing just the test page benefit almost nothing. Sincerely apologize about that.

**Comment by jspenguin2017** [comment]
Unlike uAssets, I do fix demos.
