### ISSUE TITLE
Require new bot for auto pull upstream update (The old one deprecated)

### ISSUE THREAD

**Issue by jspenguin2017** [LiCybora/NanoDefenderFirefox#89]
It's not creating pull requests anymore.

**Comment by LiCybora** [comment]
Thanks... Do you know any alternative tools for the similar things?

I will pull it manually before it fixed or I find a good alternative...

**Comment by jspenguin2017** [comment]
Why not just file a bug report?

**Comment by LiCybora** [comment]
Someone else has reported similar bug on that issue tracker already. If still not working for long I will try writing on my own.

**Comment by LiCybora** [comment]
Confirmed that the bot author discontinued the project. For now I will manually watch and pull once a day or two until I have good time for look up the GitHub API.

**Comment by jspenguin2017** [comment]
Maybe try https://github.com/wei/pull as recommended by Backstroke bot author?
