### ISSUE TITLE
[anti-adblock] https://www.bdix.org/

### ISSUE THREAD

**Issue by SeriousHoax** [LiCybora/NanoDefenderFirefox#94]
Test link:

https://www.bdix.org/

### Screenshot of the web page (including address bar and extension icons):
<a href="https://imggmi.com/view/2019/1/16/0e4046f5fa9551c184e83a1ab5cae02e-full.png.html" target="_blank"><img src="https://cdn1.imggmi.com/uploads/2019/1/16/0e4046f5fa9551c184e83a1ab5cae02e-prev.png" border="0"/></a>

### Screenshot of the console:

<a href="https://imggmi.com/view/2019/1/16/e74ef3160adf0b85099659679242b379-full.png.html" target="_blank"><img src="https://cdn1.imggmi.com/uploads/2019/1/16/e74ef3160adf0b85099659679242b379-prev.png" border="0"/></a>

### What was not right:

Detect adblock

### Environment:

- Operating System and Version: Manjaro Linux
- Browser and Version: Firefox Beta 65.0b11
- Adblocker and Version: uBlock Origin 1.17.4, Nano Defender 15.0.0.85

#### My filter lists:

<a href="https://imggmi.com/view/2019/1/16/e9414f0778667ebe101a180dcf7d07cb-full.png.html" target="_blank"><img src="https://cdn1.imggmi.com/uploads/2019/1/16/e9414f0778667ebe101a180dcf7d07cb-prev.png" border="0"/></a>

<a href="https://imggmi.com/view/2019/1/16/60e67ca354cc208da11d1ba28328ec44-full.png.html" target="_blank"><img src="https://cdn1.imggmi.com/uploads/2019/1/16/60e67ca354cc208da11d1ba28328ec44-prev.png" border="0"/></a>

### Everything else that you believe to be useful below:

This is a private tracker so you might not be able to reproduce because the warning doesn't show up until I log into the site.

**Comment by LiCybora** [comment]
Cannot reproduce without login. Registration is closed too and I cannot even create an account for testing.

**Comment by SeriousHoax** [comment]
Give me an email id for testing. I'll send you an invite to that email.

**Comment by LiCybora** [comment]
nanodefendertester@gmail.com

**Comment by SeriousHoax** [comment]
I sent you an invite. Welcome to CrazyHD is the message. Check in the spam folder if you don't receive it in inbox. 
btw, weirdly I'm seeing that popup on my Manjaro Linux only. Windows 10 doesn't show up anti adblock warning. Both are running the same extensions, filters, settings. Anyway, it's better if you login to the website personally and check if there's any issue.

**Comment by LiCybora** [comment]
Quick fix for you (Firefox only):
`bdix.org##^script:has-text(adBlockDetected)`

Or general to all browser:
`bdix.org##+js(abort-current-inline-script.js, adBlockDetected)`

Maybe I should  @okiehsch for ublock filter?

**Comment by SeriousHoax** [comment]
Ok. Thanks for the solution. So, about the fix that you provided, do I need to add that into My filters in uBlock Origin?

**Comment by LiCybora** [comment]
Yes

**Comment by SeriousHoax** [comment]
Ok thanks.

**Comment by okiehsch** [comment]
@LiCybora  Thanks, added to `uBO-filters`
