### ISSUE TITLE
Issues with another addon

### ISSUE THREAD

**Issue by rayman89** [LiCybora/NanoDefenderFirefox#95]
I noticed that when using the addon "All tabs helper" if you enable "nano defender" it will make the addon not be able to properly read wich tabs are unloaded. For example if you have a session with multiple tabs open and all suspended the addon "all tabs helper" will show them on the list greyed out but as soon as you enable "nano defender" all those tab show like normal tabs (not greyed out). I don't know why nano defender is affecting other addons (besides adblockers).

https://addons.mozilla.org/en-US/firefox/addon/all-tabs-helper/

I'm on firefox 65b12 x64 dev edition on Win7 x64

Tested on a clean profile with just nano defender and all tabs addon

**Comment by LiCybora** [comment]
I cannot reproduce. It greyed out as normal for me after. Maybe I don't get your steps to reproduce?

![image](https://user-images.githubusercontent.com/40160522/51421703-1c6ae280-1bdd-11e9-9e21-9609a9e3aa82.png)

![image](https://user-images.githubusercontent.com/40160522/51421692-e88fbd00-1bdc-11e9-9538-39cc4ae9c22e.png)

May you provide your steps to reproduce with screenshots? Because I don't use that addons and don't familiar with it.

**Comment by rayman89** [comment]
1) Have a session with only all tabs helper installed and open a few tabs
2) Select the option for firefox to "restore previous session"
3) close firefox an open it again restoring the previous session
4) If you check all tabs list you'll see them greyed out but if you now enable or install nano defender you'll notice that all the tabs will become not greyed out anymore and if you close firefox and open it again when firefox starts it will never read the starting suspended tabs as suspended.

**Comment by LiCybora** [comment]
Thanks, I can reproduce now.

FYI: The reason is the call of `chrome.webNavigation.getAllFrames` trigger tabs status update in "All Tabs Helper" extension which treat tabs as activated. I am still reviewing the code of that extension and not sure how they detect status changes of tabs however...

**Comment by LiCybora** [comment]
@jspenguin2017 Any possible side effects if we do not query discarded tabs (see my last commit)? This solve the problem, but not sure whether it would create another problem.

**Comment by jspenguin2017** [comment]
I don't think anything is using the tab store anymore, so that should be fine. 

Yea, there's some cleanup and optimization to do, Google announced their new extension API, I'll probably rewrite it when the time comes.

**Comment by LiCybora** [comment]
Fix will be available in next version

**Comment by rayman89** [comment]
Thank you for letting us know what the issue was and fixing it so quickly.

BTW you forgot to release the xpi if I'm not mistaken

**Comment by rayman89** [comment]
@LiCybora  Thank you for letting us know what the issue was and fixing it so quickly.

BTW you forgot to release the xpi if I'm not mistaken

**Comment by LiCybora** [comment]
Previously I am planning to wait until next upstream version release, as this is not quite critical.

But seems you need to use both extension, I will release 15.0.0.88 first. You will have it very soon
